### ISSUE TITLE
Make it possible to disable flake-aaa but not other linting

### ISSUE THREAD

**Issue by seddonym** [jamescooke/flake8-aaa#102]
(This is not really a bug, more of a feature request.)

Using `noqa` to turn off the linter is good feature, but I think it also turns off other linters that you'd want turned on? It would be good if there was a way of turning off only flake8-aaa.

**Comment by jamescooke** [comment]
@seddonym Flake8 will handle this, which is good news. `noqa: AAA03` will just ignore [checking for blank lines before the Act block](https://flake8-aaa.readthedocs.io/en/stable/rules.html#aaa03-expected-1-blank-line-before-act-block-found-none), for example.

BUT - there's a fix coming for [this bug](https://gitlab.com/pycqa/flake8/issues/549), which has meant that Flake8's `noqa` is not picking up up `AAA` error codes - it looks like this will be [released in v3.7.8](https://gitlab.com/pycqa/flake8/-/milestones/31).

**Comment by jamescooke** [comment]
Once that bug release of Flake8 is out, then we can:

- [ ] Add skip examples to `examples/good/noqa` - clone these to the Black examples.
- [ ] Add examples to `examples/bad` which turn off an AAA error, but still allow a Flake8 error to bubble.
- [ ] Update docs on how to [disable AAA checking in code](https://flake8-aaa.readthedocs.io/en/stable/commands.html#disabling-flake8-aaa-selectively).

**Comment by jamescooke** [comment]
@seddonym This all works now as long as you use `flake8>=3.7.8`. It's probably a good idea to use the latest `v0.7.0` because the lines returned for AAA03 and AAA04 have been changed.
