### ISSUE TITLE
Readme summary could be misleading

### ISSUE THREAD

**Issue by seddonym** [jamescooke/flake8-aaa#103]
I thought, from the TL;DR at the beginning of the README, that it simply checks for the "# ARRANGE","# ACT" and "# ASSERT" comments in every test. I think it would be worth clarifying that it does static analysis based on a few rules. Maybe some examples would be better?

**Comment by jamescooke** [comment]
Thanks @seddonym ... I'm going to close this as resolved by #104 .

Feel free to reopen, especially if you have any suggestions on how we might improve it further.
